name: EmpireWand
author: Patrycioss
website: https://github.com/Patrycioss/EmpireWandPlugin
version: '${project.version}'
main: me.patrycioss.empirewand.EmpireWand
api-version: 1.19
commands:
  empirewand:
    description: Gives the player an empire wand
    usage: /empirewand [target player]
    aliases: [ew, ewand]

  setempirewandrange:
    description: Set the range of your wand
    usage: /setempirewandrange [range]
    aliases: [erange, ewandrange]

  setempirewandexplosionpower:
    description: Set the power of explosions caused by the wand
    usage: /setempirewandexplosionpower [explosionpower]
    aliases: [ewandexplosionpower, ewexplosionpower, ewplopower, ewexplopower]

permissions:
  EmpireWand.setrange:
    description: Allows setrange command
    default: not op

  EmpireWand.setexplosionpower:
    description: Allows setexplosionpower command
    default: op

  test.*:
    description: Wildcard permission
    default: op
    children:
      EmpireWand.setrange: true
      EmpireWand.setexplosionpower: true
