name: EmpireWand
author: Patrycioss
website: https://github.com/Patrycioss/EmpireWandPlugin
version: '${project.version}'
main: me.patrycioss.empirewand.EmpireWand
api-version: 1.19
commands:
  setrange:
    description: Set the range of your wand
    usage: "Usage: /<setrange> [value]"

  setexplosionpower:
    description: Set the power of explosions caused by the wand
    usage: "Usage: /<setexplosionpower> [value]"

permissions:
  EmpireWand.setrange:
    description: Allows setrange command
    default: not op

  EmpireWand.setexplosionpower:
    description: Allows setexplosionpower command
    default: op

  test.*:
    description: Wildcard permission
    default: op
    children:
      EmpireWand.setrange: true
      EmpireWand.setexplosionpower: true
